version: '3.7'

services:
  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - redis
      - postgres
    networks:
      - default
    environment:
      BOT_PUBLIC_PORT: 80
      TELEGRAM_TOKEN:
      DOMAIN:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_FSM:
      REDIS_DB_JOBSTORE:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      RCON_PASSWORD:
      MC_SERVER_IP:
      MAIN_GROUP_ID:

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data
    networks:
      - default
    # ports:
    #   - "6379:6379"

  postgres:
    image: postgres:alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

volumes:
  redis-data:
  postgres-data:

networks:
  default:
    driver: overlay